# This is a config for E2B sandbox template.
# You can use template ID (u7kddvmyshv0zpc7hp6n) or template name (lovable-clone-nextjs-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-clone-nextjs-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-nextjs-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-nextjs-3')

team_id = "29e5854e-2fca-41bf-9c84-72cfd4120db1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-nextjs-3"
template_id = "u7kddvmyshv0zpc7hp6n"
